version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: github.com/centrifugal/centrifuge # updating manually.
    groups:
      go-packages:
        patterns:
          - '*'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
