version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    groups:
      go-packages:
        patterns: '*'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
