project_name: centrifugo
release:
  github:
    owner: centrifugal
    name: centrifugo
  name_template: '{{.Tag}}'
  # If set to true, will not auto-publish the release.
  draft: true
  # If set to true, will mark the release as not ready for production.
  prerelease: true
brew:
  commit_author:
    name: Alexander Emelin
    email: frvzmb@gmail.com
  install: bin.install "centrifugo"
  skip_upload: true
builds:
- goos:
  - linux
  - darwin
  - freebsd
  - windows
  goarch:
  - amd64
  - "386"
  - arm
  - arm64
  ignore:
    - goos: darwin
      goarch: "386"
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: arm64
    - goos: windows
      goarch: "386"
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: freebsd
      goarch: "386"
    - goos: freebsd
      goarch: arm
    - goos: freebsd
      goarch: arm64
  main: .
  ldflags: -s -w -X main.VERSION={{.Version}}
  binary: centrifugo
  env:
    # https://github.com/goreleaser/goreleaser/issues/225
    - CGO_ENABLED=0
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
  format_overrides:
    - goos: windows
      format: zip
# nfpm:
#   name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
#     }}v{{ .Arm }}{{ end }}'
#   homepage: https://github.com/centrifugal/centrifugo
#   maintainer: Alexander Emelin <frvzmb@gmail.com>
#   description: Centrifugo – real-time messaging server.
#   license: MIT
#   formats:
#     - deb
#     - rpm
#   bindir: /usr/local/bin
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
dockers:
  -
    binary: centrifugo
    goos: linux
    goarch: amd64
    goarm: ''
    image: fzambia/centrifugo2
    tag_templates:
    - "{{ .Tag }}"
    - "v{{ .Major }}"
    - "v{{ .Major }}.{{ .Minor }}"
    - latest
