name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release with Go ${{ matrix.go-version }}
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Install rpm
        run: sudo apt-get install rpm

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install gox
        run: GO111MODULE=off go get github.com/mitchellh/gox

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Release on Github
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes=misc/release/notes.md
        env:
          # note custom secret here since we need access to Centrifugo Homebrew repo.
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

#      - name: Release on Github
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: misc/release/release.sh --release-notes=misc/release/notes.md

      - name: Release on Packagecloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: misc/scripts/travis_packagecloud.sh
