name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release with Go ${{ matrix.go-version }}
    environment: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.2]
    steps:
      - name: Install rpm
        run: sudo apt-get install rpm

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install gox
        run: GO111MODULE=off go get github.com/mitchellh/gox

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      
      - name: "Set up Docker buildx"
        uses: "docker/setup-buildx-action@v1"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build DEB and RPM packages
        run: misc/scripts/release_package.sh

      - name: Release on Github
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes=misc/release/notes.md
        env:
          # note custom secret here since we need access to Centrifugo Homebrew repo.
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          UNIX_NOW: ${{ env.UNIX_NOW }}

      - name: Release on Packagecloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: misc/scripts/release_packagecloud.sh
